version: '3'
services:
  vicon-driver:
    build:
      context: ./
      args:
        # Change to Vicon server IP address. The current value WILL NOT WORK.
        vicon_server_ip: 127.0.0.1
    container_name: vicon-driver-c
    tty: true
    image: vicon-driver
    network_mode: "host"
    environment:
      # Substitute "HOSTNAME" in both environment variable for the name of your computer.
      ROS_HOSTNAME: HOSTNAME
      ROS_MASTER_URI: http://HOSTNAME:11311
